### ISSUE TITLE
Enable Device Configuration

### ISSUE THREAD

**Issue by alexanderkjones** [alexanderkjones/GM_V1#2]
**Story**
As a Manufacturer I want to be able to press a device button to wake up the device and enter config mode.

**Desc**
The devices primary state is sleep mode or logging mode. A physical button is used to wake the system and enter configuration mode. The ESP8266 has no NV Ram and only 1 wake pin which is shared with the WTD. The ESP8266 cannot discern if it has been woken by the WDT or the hardware button. EEPROM and RTC must be used to identify if interrupt is before a sleep interrupt or a hardware interrupt variable signifying a user interrupt.

**Acceptance Criteria**
- The user can press the hardware button and wake the device to AP mode from sleep cycle
- The user can see the AP network on their mobile device
- The user is displayed a "Hello World" after connecting to AP and going to 192.168.4.1
- The device goes to sleep after 30 sec from last request to 192.168.4.1

**Comment by alexanderkjones** [comment]
@JLJTGR will you be available to look at these new issues next week?

**Comment by JLJTGR** [comment]
There's a few things wrong with the summary due to how the hardware actually works.

- The hardware button is on GPIO 13 and not the reset line.  Thus it is impossible for the button to wake the device.
- The hardware button is a GPIO, thus it is easy to know if the button is pressed rather than the WDT resetting the device.
- Since the button cannot wake the device, it must be polled when the device does wake up via the WDT, meaning the sleep period is the polling period of the button while asleep.
- The EEPROM is unnecessary for this logic and the RTC is only useful.

**Comment by JLJTGR** [comment]
Basic sequence:

1. Device sleeps in periods of 5 seconds
2. If the user holds down the button until one of those periods has passed, the device does not go back to sleep and the LED is illuminated, the local AP is started and the web server at 192.168.4.1 is available
3. If the button is pressed or the web server root is accessed, the timeout is reset
4. If the timeout reaches 30 seconds, the device sleeps, powering down all of the above

**Comment by alexanderkjones** [comment]
@JLJTGR current solution is great. We intended to tie the button to reset to avoid the wake cycles beyond the log interval. We'll measure the power usage and re-dress if it's an issue.
